sonar.projectKey=xsteve-devops_e-commerce-devops-app
sonar.organization=xsteve-devops

sonar.projectName=e-commerce-devops-app
sonar.sources=src/ad/src/main/java
sonar.java.binaries=src/ad/build/classes/java/main

sonar.sourceEncoding=UTF-8